feat: Create grpc base for event service
UnspokenTeam/Calendar pull request #1
Opened 2024-03-20 20:24 UTC by ZixMai

Created grpc server
Created event to grpc event converter
Created grpc model
Created grpc service implementation
Created docstrings to each def and class

2024-03-20 21:22 UTC, Nhsdkk requested changes
Check my comments

2024-03-20 21:22 UTC, Nhsdkk commented on event_service/src/event_service_impl.py
> +    ...
Delete unnecessary dots here

2024-03-20 21:22 UTC, Nhsdkk commented on event_service/src/event_service_impl.py
> +                start=datetime(2024, 3, 19, 10, 0),  # Example start time
Delete unnecessary comments

2024-03-20 21:22 UTC, Nhsdkk commented on event_service/src/event_service_impl.py
> +        StandardResponse
Rename StandardResponse to BaseResponse for convenience

2024-03-20 21:22 UTC, Nhsdkk commented on event_service/src/models/event.py
> +    ...
Delete unnecessary dots here

2024-03-20 21:22 UTC, Nhsdkk commented on event_service/proto/event_service.proto
> +message StandardResponse {
Rename StandardResponse to BaseResponse for convenience

2024-03-21 06:16 UTC, Nhsdkk approved these changes
LGTM

2024-03-21 10:10 UTC, MaxPlays35 requested changes

2024-03-21 10:10 UTC, MaxPlays35 commented on event_service/pyproject.toml
>  authors = ["Nhsdkk <38581029+Nhsdkk@users.noreply.github.com>"]
Add other authors please

2024-03-21 10:10 UTC, MaxPlays35 commented on event_service/src/event_service_impl.py
> +from proto.event_service_pb2 import (
Import using asterisk or 
```python
import proto.event_service_pb2 as proto
```

2024-03-21 10:26 UTC, MaxPlays35 approved these changes

2024-03-21 10:28 UTC, MaxPlays35 approved these changes

2024-03-21 10:52 UTC, Nhsdkk approved these changes
LGTM

2024-03-21 10:55 UTC, merged