Feat: Create new request methods for notification service
UnspokenTeam/Calendar pull request #105
Opened 2024-05-07 07:01 UTC by ZixMai

1.  Added get_notifications_by_event_id method
2.  Added search by time interval for get_notifications_by_author_id

2024-05-07 16:53 UTC, Nhsdkk requested changes
Make changes

2024-05-07 16:53 UTC, Nhsdkk commented on notification_service/repository/mock_notification_repository.py
> +        prisma.errors.PrismaError
This function does not throw this error

2024-05-07 19:21 UTC, MaxPlays35 approved these changes

2024-05-08 11:38 UTC, Nhsdkk approved these changes
LGTM

2024-05-08 11:38 UTC, merged