Feat: add jwt controller
UnspokenTeam/Calendar pull request #15
Opened 2024-03-25 15:25 UTC by Nhsdkk

1) Switch from jwcrypto to pyjwt
2) Add jwt controller

2024-03-25 15:44 UTC, ZixMai requested changes

2024-03-25 15:44 UTC, ZixMai commented on identity_service/utils/jwt_controller.py
> +    """
add empty string

2024-03-25 17:42 UTC, Nhsdkk commented on identity_service/utils/jwt_controller.py
> +    """
fixed

2024-03-25 18:14 UTC, ZixMai approved these changes

2024-03-26 18:06 UTC, MaxPlays35 approved these changes

2024-03-26 18:55 UTC, merged