feat: create grpc base for identity service
UnspokenTeam/Calendar pull request #2
Opened 2024-03-20 21:28 UTC by Nhsdkk

1) Created grpc server
2) Created identity server implementation
3) Created all method declarations in proto file
4) Mapped all method declarations in python to proto
5) Created User dataclass
6) Wrote docstrings for all added functions

2024-03-21 08:08 UTC, ZixMai approved these changes

2024-03-21 10:20 UTC, MaxPlays35 requested changes

2024-03-21 10:20 UTC, MaxPlays35 commented on identity_service/proto/identity_service.proto
I think this file is too big.
Maybe divide this file into several files. For example Authentication.proto, User.proto something like that.

2024-03-21 10:20 UTC, MaxPlays35 commented on identity_service/src/identity_service_impl.py
> +from proto.identity_service_pb2 import (
Import using asterisk or
```python
import proto.identity_service_pb2 as proto
```

2024-03-22 13:12 UTC, MaxPlays35 approved these changes

2024-03-22 16:12 UTC, ZixMai approved these changes

2024-03-22 19:15 UTC, merged