feat: grpc requests methods
UnspokenTeam/Calendar pull request #26
Opened 2024-03-28 16:28 UTC by ZixMai

1) Added async grpc requests methods 2) Name changes in protobuf file
3) Added event repository arg in event service impl method in main
4) Changed docstrings
5) Added inheritance in EventRepositoryImpl class
6) Added and sorted some imports
7) Added logging to postgres_client.py 8) Small changes in arguments format

2024-03-28 16:32 UTC, MaxPlays35 approved these changes
Approved

2024-03-29 20:40 UTC, Nhsdkk requested changes
check the review and mate changes accordingly

2024-03-29 20:40 UTC, Nhsdkk commented on event_service/repository/event_repository_impl.py
> +            where={"id": event_id}
Check that deleted at is None

2024-03-29 20:40 UTC, Nhsdkk commented on event_service/repository/event_repository_impl.py
> +            where={"id": {"in": [event_id for event_id in events_ids.ids]}}
Check that deleted at is None

2024-03-29 20:40 UTC, Nhsdkk commented on event_service/repository/mock_event_repository.py
> +        self, events_ids: ListOfEventsIds
Make this method accept event_ids: List[str]

2024-03-29 20:40 UTC, Nhsdkk commented on event_service/repository/mock_event_repository.py
> +        if self._events is None or len(self._events) == 0:
self._events should not be none

2024-03-29 20:40 UTC, Nhsdkk commented on event_service/repository/mock_event_repository.py
> +            if self._events[index].author_id == event.author_id:
This check is useless

2024-03-29 20:40 UTC, Nhsdkk commented on event_service/src/event_service_impl.py
> +            return proto.EventResponse(status_code=200, event=event)
should be event= event.to_grpc_event()

2024-03-29 20:40 UTC, Nhsdkk commented on event_service/src/event_service_impl.py
> +                status_code=200, events=proto.ListOfEvents(events=events)
should use generator to convert events to grpc events

2024-03-29 20:40 UTC, Nhsdkk commented on event_service/src/event_service_impl.py
> +                status_code=200, events=proto.ListOfEvents(events=events)
should use generator to convert events to grpc events

2024-03-29 20:40 UTC, Nhsdkk commented on event_service/src/event_service_impl.py
> +                status_code=200, events=proto.ListOfEvents(events=events)
should use generator to convert events to grpc events

2024-03-29 20:40 UTC, Nhsdkk commented on event_service/src/models/event.py
> +        exclude_set = set(exclude if exclude is not None else []) | {"id", "author_id"}
no need to exclude author_id

2024-03-29 20:44 UTC, Nhsdkk commented
When you get events you should return all event data, including created_at and deleted_at, and also this field should be modifiable in update_event

2024-03-30 20:43 UTC, Nhsdkk requested changes
Check and make changes

2024-03-30 20:43 UTC, Nhsdkk commented on event_service/src/event_service_impl.py
> +                events_ids=[event_id for event_id in request.events_ids.ids]
Just write list(request.events_ids.ids)

2024-03-30 20:43 UTC, Nhsdkk commented on event_service/src/models/event.py
> +            deleted_at=datetime.fromtimestamp(
check for None

2024-03-31 15:41 UTC, Nhsdkk approved these changes
LGTM

2024-03-31 15:41 UTC, merged