Feat/add repository for invite service
UnspokenTeam/Calendar pull request #29
Opened 2024-04-02 18:47 UTC by skelet0no

1. Added repository files
2. Change docstrings
3. Added methods in invite.py
4. Added db connecting python file
5. Added value not found file in errors
6. Added prisma schema
7. Added class decorator singleton

2024-04-02 20:01 UTC, ZixMai requested changes
Checked by Elena Letuchaya.

2024-04-02 20:01 UTC, ZixMai commented on invite_service/repository/mock_invite_repository.py
> +        Updates invite that has the same id as provided invite object inside db or throws an exception.
remove "or throws an exception" in both methods

2024-04-02 20:01 UTC, ZixMai commented on invite_service/repository/mock_invite_repository.py
> +        prisma.errors.PrismaError
this method doesnt raise any error from prisma remove it pls

2024-04-02 20:01 UTC, ZixMai commented on invite_service/repository/mock_invite_repository.py
> +        Value Not Found Error
Error name must be written without empty spaces

2024-04-02 20:01 UTC, ZixMai commented on invite_service/repository/mock_invite_repository.py
> +        Value Not Found Error
Error name must be written without empty spaces

2024-04-02 20:01 UTC, ZixMai commented on invite_service/repository/invite_repository_impl.py
> +    async def get_all_invites(self, invite: Invite) -> List[Invite]:
you dont need invite to request all invites, remove it from parameters and from docstring

2024-04-02 20:01 UTC, ZixMai commented on invite_service/src/invite_service_impl.py
Add get all invites method to invite service impl file and into class docstring and add repository to init

2024-04-02 20:01 UTC, ZixMai commented on invite_service/repository/mock_invite_repository.py
Add get all invites and get invites by invitee id methods to file and into class docstring

2024-04-02 20:01 UTC, ZixMai commented on invite_service/repository/invite_repository_interface.py
> +    async def get_all_invites(self, invite: Invite) -> List[Invite]:
we dont need invite object to request all invites, remove it from parameters

2024-04-02 20:01 UTC, ZixMai commented on invite_service/repository/invite_repository_impl.py
> +    async get_all_invites(invite)
remove invite from parameters

2024-04-02 20:01 UTC, ZixMai commented on invite_service/repository/invite_repository_interface.py
> +    async get_all_invites(invite)
we dont need invite object to request all invites, remove it from parameters

2024-04-02 20:01 UTC, ZixMai commented on invite_service/repository/invite_repository_impl.py
> +        ] = await self._db_client.db.invite.find_many(where={"id": author_id})
check if deleted_at is None

2024-04-02 20:01 UTC, ZixMai commented on invite_service/src/models/invite.py
add created_at and deleted_at fields to dataclass, add __post_init__ for created_at field, add this fields to to_grpc_invite method using FromDatetime. Check event.py code in master branch for instructions

2024-04-02 20:01 UTC, ZixMai commented on invite_service/repository/mock_invite_repository.py
> +        invites = [invite for invite in self._invites if invite.author_id == author_id]
check for deleted_at is None

2024-04-02 20:01 UTC, ZixMai commented on invite_service/repository/mock_invite_repository.py
> +            if self._invites[i].id == invite_id
check for deleted_at is None

2024-04-04 17:47 UTC, ZixMai requested changes
add post init !!!!! check my comments and fix all problems

2024-04-04 17:47 UTC, ZixMai commented on invite_service/src/invite_service_impl.py
> +        self, request: None, context: grpc.ServicerContext
0_0 request: None?

2024-04-04 17:47 UTC, ZixMai commented on invite_service/repository/invite_repository_impl.py
remove parameters from docstring...

2024-04-04 18:07 UTC, ZixMai requested changes
:(

2024-04-04 18:07 UTC, ZixMai commented on invite_service/repository/invite_repository_interface.py
> +        invite : Invite
remove parameters from docstring

2024-04-04 18:07 UTC, ZixMai commented on invite_service/repository/mock_invite_repository.py
> +        invitee_id : List[str]
it takes str, not List[str] change it in the args and in docstring

2024-04-06 11:28 UTC, ZixMai approved these changes

2024-04-07 16:50 UTC, MaxPlays35 approved these changes
Done very well

2024-04-08 19:04 UTC, Nhsdkk requested changes
Make changes

2024-04-08 19:04 UTC, Nhsdkk commented on invite_service/repository/invite_repository_impl.py
> +            invitee_id object.
Should be invitee id

2024-04-08 19:04 UTC, Nhsdkk commented on invite_service/repository/invite_repository_impl.py
> +                "id": {"in": [invite_id for invite_id in invitee_id]},
Should be "id": invitee_id,

2024-04-08 19:04 UTC, Nhsdkk commented on invite_service/repository/invite_repository_interface.py
> +            invitee_id object.
Should be just invitee id

2024-04-08 19:04 UTC, Nhsdkk commented on invite_service/repository/invite_repository_impl.py
> +    async get_all_invites()
Sort please

2024-04-08 19:04 UTC, Nhsdkk commented on invite_service/repository/mock_invite_repository.py
> +    async get_invites(author_id)
rename function to get_invites_by_author_id

2024-04-08 19:04 UTC, Nhsdkk commented on invite_service/repository/invite_repository_interface.py
> +    async get_invites(author_id)
rename function to get_invites_by_author_id

2024-04-08 19:04 UTC, Nhsdkk commented on invite_service/repository/invite_repository_interface.py
> +    async def get_invites(self, author_id: str) -> List[Invite]:
rename function to get_invites_by_author_id

2024-04-08 19:04 UTC, Nhsdkk commented on invite_service/repository/invite_repository_impl.py
> +    async get_invites(author_id)
rename function to get_invites_by_author_id

2024-04-08 19:04 UTC, Nhsdkk commented on invite_service/repository/invite_repository_impl.py
> +    async def get_invites(self, author_id: str) -> List[Invite]:
rename function to get_invites_by_author_id

2024-04-08 19:04 UTC, Nhsdkk commented on invite_service/repository/mock_invite_repository.py
> +    async def get_invites(self, author_id: str) -> List[Invite]:
rename function to get_invites_by_author_id

2024-04-08 19:04 UTC, Nhsdkk commented on invite_service/repository/mock_invite_repository.py
> +            if invite.id in invitee_id and invite.deleted_at is None
Should be if invite.id == invitee_id and invite.deleted_at is None

2024-04-08 19:04 UTC, Nhsdkk commented on invite_service/repository/mock_invite_repository.py
> +        )
Catch StopIteration and throw ValueNotFoundError

2024-04-08 19:04 UTC, Nhsdkk commented on invite_service/repository/mock_invite_repository.py
> +        if self._invites[index].author_id == invite.author_id:
Permission check should not be on repository level

2024-04-08 19:04 UTC, Nhsdkk commented on invite_service/src/invite_service_impl.py
>      def get_invites_by_user_id(
rename function to get_invites_by_author_id

2024-04-09 07:29 UTC, Nhsdkk approved these changes
LGTM

2024-04-09 07:29 UTC, merged