Feat: added pagination
UnspokenTeam/Calendar pull request #30
Opened 2024-04-03 11:35 UTC by ZixMai

1. added pagination to requests
2. added more fields to protobuf file for pagination

2024-04-03 20:58 UTC, Nhsdkk requested changes
Check my review

2024-04-03 20:58 UTC, Nhsdkk commented on event_service/proto/event_service.proto
> +  int32 page_number = 3;
Use int64

2024-04-05 09:23 UTC, Nhsdkk approved these changes
LGTM

2024-04-05 16:50 UTC, MaxPlays35 approved these changes

2024-04-06 08:37 UTC, Nhsdkk commented on event_service/proto/event_service.proto
> +  int32 page_number = 3;
Fixed

2024-04-06 08:37 UTC, Nhsdkk approved these changes
LGTM

2024-04-06 08:38 UTC, merged