feat: add pagination
UnspokenTeam/Calendar pull request #31
Opened 2024-04-05 21:27 UTC by Nhsdkk

1) Add pagination to get_all_users method
2) Add pagination to get_users_by_ids method

2024-04-05 21:31 UTC, MaxPlays35 requested changes

2024-04-05 21:31 UTC, MaxPlays35 commented on identity_service/proto/get_user.proto
> +  int64 page = 1;
Maybe use uint?

2024-04-05 21:31 UTC, MaxPlays35 commented on identity_service/proto/get_user.proto
> +  int64 page = 1;
Same here

2024-04-05 21:31 UTC, MaxPlays35 commented on identity_service/repository/user_repository_interface.py
> +            Page index
Page index must be nonnegative

2024-04-05 21:31 UTC, MaxPlays35 commented on identity_service/repository/user_repository_interface.py
> +            Page index
Same here

2024-04-05 22:33 UTC, Nhsdkk commented on identity_service/proto/get_user.proto
> +  int64 page = 1;
fixed

2024-04-05 22:33 UTC, Nhsdkk commented on identity_service/repository/user_repository_interface.py
> +            Page index
fixed

2024-04-05 22:33 UTC, Nhsdkk commented on identity_service/repository/user_repository_interface.py
> +            Page index
fixed

2024-04-05 22:33 UTC, Nhsdkk commented on identity_service/proto/get_user.proto
> +  int64 page = 1;
fixed

2024-04-06 09:20 UTC, MaxPlays35 approved these changes

2024-04-06 10:00 UTC, ZixMai approved these changes

2024-04-06 10:00 UTC, merged