feat: add grpc requests for invite service
UnspokenTeam/Calendar pull request #37
Opened 2024-04-10 18:51 UTC by skelet0no

1. add messages in proto
2. add get invite by invite id method

2024-04-11 06:56 UTC, Nhsdkk requested changes
Make changes

2024-04-11 06:56 UTC, Nhsdkk commented on invite_service/src/invite_service_impl.py
> +            )
check if user is allowed to get the invite

2024-04-11 06:56 UTC, Nhsdkk commented on invite_service/src/invite_service_impl.py
> +                invitee_id=request.invite_id,
maybe invitee_id

2024-04-11 06:56 UTC, Nhsdkk commented on invite_service/src/invite_service_impl.py
> +            invite = Invite.from_grpc_invite(request.invite)
check if user can modify invite

2024-04-11 06:56 UTC, Nhsdkk commented on invite_service/src/invite_service_impl.py
> +            await self._invite_repository.delete_invite(invite_id=request.invite_id)
check if user can delete invite

2024-04-11 18:39 UTC, ZixMai requested changes
CHECK FOR ADMIN USER TYPE, DONT RESOLVE CONVERSATION IF YOU DONT UNDERSTAND PROBLEM

2024-04-11 18:39 UTC, ZixMai commented on invite_service/proto/invite_service.proto
> +  GrpcInvite invite = 2;
must be optional

2024-04-11 18:39 UTC, ZixMai commented on invite_service/proto/invite_service.proto
>    rpc get_invites_by_invitee_id(GetInviteeByInviteIdRequest) returns (InvitesResponse){}
must be GetInvitesByInviteeIdRequest

2024-04-11 18:39 UTC, ZixMai commented on invite_service/proto/invite_service.proto
>    rpc get_all_invites(google.protobuf.Empty) returns (InvitesResponse){}
you need to throw user in request to check user type, add new message RequestingUser

2024-04-11 18:39 UTC, ZixMai commented on invite_service/repository/invite_repository_impl.py
> +    async def get_invite_by_invite_id(self, invite_id: str) -> Invite:
add this method to class methods docstrong

2024-04-11 18:39 UTC, ZixMai commented on invite_service/src/invite_service_impl.py
> +            await self._invite_repository.create_invite(invite=invite)
check if user can create invite

2024-04-11 18:41 UTC, ZixMai requested changes

2024-04-11 18:41 UTC, ZixMai commented on invite_service/src/invite_service_impl.py
>          self, request: Empty, context: grpc.ServicerContext
add requesting user from proto

2024-04-11 18:41 UTC, ZixMai commented on invite_service/src/invite_service_impl.py
> +            if request.user.type != proto.GrpcUserType.ADMIN:
WHERE DID YOU FIND USER TYPE IN EMPTY OBJECT

2024-04-13 10:37 UTC, ZixMai requested changes
Dont resolve any conversations again... And read old problem descriptions. add admin user type check

2024-04-13 10:37 UTC, ZixMai commented on invite_service/proto/invite_service.proto
> +  GrpcInvite invite = 2;
remove this field

2024-04-13 10:37 UTC, ZixMai commented on invite_service/proto/invite_service.proto
> +  rpc create_invite(GrpcInvite) returns (BaseResponse){}
must be InviteRequest instead of GrpcInvite

2024-04-13 10:37 UTC, ZixMai commented on invite_service/proto/invite_service.proto
> +  rpc update_invite(GrpcInvite) returns (BaseResponse){}
must be InviteRequest instead of GrpcInvite

2024-04-13 10:37 UTC, ZixMai commented on invite_service/proto/invite_service.proto
>  message GetInviteeByInviteIdRequest {
remove this message

2024-04-13 10:37 UTC, ZixMai commented on invite_service/proto/invite_service.proto
> +  GrpcInvite invite = 2;
remove this field

2024-04-13 10:37 UTC, ZixMai commented on invite_service/repository/invite_repository_impl.py
> +            raise ValueNotFoundError("Invites not found")
change was to were in docstring (not only in this method, check other methods too)

2024-04-13 10:37 UTC, ZixMai commented on invite_service/repository/invite_repository_interface.py
> +            No invites was found for given author id.
invites were*, check for this mistake in other docstrings

2024-04-13 10:37 UTC, ZixMai commented on invite_service/proto/invite_service.proto
> +  string author_id = 1;
add user field

2024-04-13 10:37 UTC, ZixMai commented on invite_service/proto/invite_service.proto
>    string invitee_id = 1;
add user field

2024-04-13 10:37 UTC, ZixMai commented on invite_service/src/invite_service_impl.py
> +        try:
add full user type check

2024-04-13 10:37 UTC, ZixMai commented on invite_service/src/invite_service_impl.py
> +            invites = await self._invite_repository.get_invites_by_invitee_id(
add full user type check

2024-04-13 10:37 UTC, ZixMai commented on invite_service/src/invite_service_impl.py
> +                raise PermissionDeniedError("Permission denied")
add raises to docstring

2024-04-13 10:37 UTC, ZixMai commented on invite_service/src/invite_service_impl.py
> +                raise PermissionDeniedError("Permission denied")
add raises to docstring

2024-04-13 10:37 UTC, ZixMai commented on invite_service/src/invite_service_impl.py
> +                raise PermissionDeniedError("Permission denied")
add raises to docstring

2024-04-13 10:37 UTC, ZixMai commented on invite_service/src/invite_service_impl.py
> +                return proto.BaseResponse(status_code=403, message="Permission denied")
use PermissionDeniedError instead

2024-04-13 10:37 UTC, ZixMai commented on invite_service/src/invite_service_impl.py
> +                raise PermissionDeniedError("Permission denied")
add raises to docstring

2024-04-13 10:37 UTC, ZixMai commented on invite_service/src/invite_service_impl.py
> +            invite = Invite.from_grpc_invite(request.invite)
remove this line

2024-04-13 10:37 UTC, ZixMai commented on invite_service/src/invite_service_impl.py
> +            if request.user.id != invite.author_id:
move this code block under invite getting

2024-04-13 10:42 UTC, ZixMai requested changes

2024-04-13 10:42 UTC, ZixMai commented on invite_service/src/invite_service_impl.py
> +            invite = Invite.from_grpc_invite(request.invite)
must be request by invite id to db instead

2024-04-15 19:40 UTC, Nhsdkk commented
line 165 in invite_repository_impl.py should be "invitee_id": invitee_id instead of "id": invitee_id

2024-04-15 20:09 UTC, Nhsdkk requested changes
Make changes

2024-04-15 20:09 UTC, Nhsdkk commented on invite_service/proto/invite_service.proto
> +  GrpcUser user = 2;
rename to requesting_user

2024-04-15 20:09 UTC, Nhsdkk commented on invite_service/proto/invite_service.proto
> +  string author_id = 1;
fixed by him

2024-04-15 20:09 UTC, Nhsdkk commented on invite_service/proto/invite_service.proto
> +  GrpcUser user = 2;
rename to requesting_user

2024-04-15 20:09 UTC, Nhsdkk commented on invite_service/proto/invite_service.proto
> +  GrpcUser user = 2;
rename to requesting_user

2024-04-15 20:09 UTC, Nhsdkk commented on invite_service/proto/invite_service.proto
>    string invitee_id = 1;
fixed by him

2024-04-15 20:09 UTC, Nhsdkk commented on invite_service/proto/invite_service.proto
> +  GrpcUser user = 2;
rename to requesting_user

2024-04-15 20:09 UTC, Nhsdkk commented on invite_service/proto/invite_service.proto
> +  GrpcUser user = 1;
rename to requesting_user

2024-04-15 20:09 UTC, Nhsdkk commented on invite_service/repository/invite_repository_impl.py
> +    async def get_invite_by_invite_id(self, invite_id: str) -> Invite:
fixed by him

2024-04-15 20:09 UTC, Nhsdkk commented on invite_service/repository/invite_repository_impl.py
> +            raise ValueNotFoundError("Invites not found")
fixed by him

2024-04-15 20:09 UTC, Nhsdkk commented on invite_service/src/invite_service_impl.py
> +    _invite_repository: InviteRepositoryInterface
No docstring here

2024-04-15 20:09 UTC, Nhsdkk commented on invite_service/src/invite_service_impl.py
> +        try:
fixed by him

2024-04-15 20:09 UTC, Nhsdkk commented on invite_service/src/invite_service_impl.py
> +                request.user.id != invite.author_id
invitee can also access this

2024-04-15 20:09 UTC, Nhsdkk commented on invite_service/src/invite_service_impl.py
> +            invites = await self._invite_repository.get_invites_by_invitee_id(
fixed by him

2024-04-15 20:09 UTC, Nhsdkk commented on invite_service/src/invite_service_impl.py
> +            if (
Make this function accessible to anyone

2024-04-15 20:09 UTC, Nhsdkk commented on invite_service/src/invite_service_impl.py
> +            invite = Invite.from_grpc_invite(request.invite)
fixed

2024-04-15 20:13 UTC, Nhsdkk commented on invite_service/src/invite_service_impl.py
> +            await self._invite_repository.delete_invite(invite_id=request.invite_id)
fixed

2024-04-15 20:14 UTC, ZixMai requested changes

2024-04-15 20:14 UTC, ZixMai commented on invite_service/repository/invite_repository_impl.py
> +            No invites were found for given invitee id.
Great, now switch 146 line invitee id object to Invitee's id :D

2024-04-15 20:14 UTC, ZixMai commented on invite_service/repository/invite_repository_interface.py
>          prisma.errors.PrismaError
change 109'th line to Invitee's id.

2024-04-15 20:40 UTC, ZixMai requested changes

2024-04-15 20:40 UTC, ZixMai commented on invite_service/src/invite_service_impl.py
> +        PermissionDeniedError
Must be a raises block

2024-04-17 22:28 UTC, ZixMai requested changes
5 more...

2024-04-17 22:28 UTC, ZixMai commented on invite_service/repository/invite_repository_interface.py
> +    async get_invite_by_invite_id(invitee_id)
change argument to invite id

2024-04-17 22:28 UTC, ZixMai commented on invite_service/repository/invite_repository_impl.py
> +                where={"id": author_id, "deleted_at": None}
change "id" field to "author_id"

2024-04-17 22:28 UTC, ZixMai commented on invite_service/src/invite_service_impl.py
> +        self, request: proto.InvitesByAuthorIdRequest, context: grpc.ServicerContext
change parameter in docstring

2024-04-17 22:28 UTC, ZixMai commented on invite_service/src/invite_service_impl.py
> +        self, request: proto.InviteRequest, context: grpc.ServicerContext
change parameter in docstring

2024-04-17 22:28 UTC, ZixMai commented on invite_service/src/invite_service_impl.py
> +        self, request: proto.InviteRequest, context: grpc.ServicerContext
change parameter in docstring

2024-04-18 15:41 UTC, ZixMai approved these changes

2024-04-19 11:31 UTC, MaxPlays35 approved these changes

2024-04-19 12:12 UTC, Nhsdkk commented
Please merge main into this branch and make changes for imports

2024-04-19 18:43 UTC, Nhsdkk approved these changes
LGTM

2024-04-19 18:52 UTC, ZixMai approved these changes

2024-04-20 10:24 UTC, ZixMai approved these changes

2024-04-20 10:24 UTC, ZixMai commented on invite_service/repository/invite_repository_impl.py
> +            raise ValueNotFoundError("Invitee's not found")
must be invite not found

2024-04-20 10:24 UTC, ZixMai commented on invite_service/src/invite_service_impl.py
> +            return proto.InvitesResponse(status_code=404, message="Invite not found")
must be invites not found

2024-04-20 10:24 UTC, ZixMai commented on invite_service/src/invite_service_impl.py
> +            return proto.InviteResponse(status_code=404, message="Invites not found")
must be invite not found

2024-04-20 10:24 UTC, ZixMai commented on invite_service/src/invite_service_impl.py
> +        except ValueNotFoundError:
remove this exception

2024-04-20 10:24 UTC, ZixMai commented on invite_service/src/invite_service_impl.py
> +        ------
add ValueNotFound to raises

2024-04-20 10:24 UTC, ZixMai commented on invite_service/src/invite_service_impl.py
>          ------
add ValueNotFound to raises

2024-04-20 10:24 UTC, ZixMai commented on invite_service/src/invite_service_impl.py
> +        ------
add ValueNotFound to raises

2024-04-20 10:24 UTC, ZixMai commented on invite_service/src/invite_service_impl.py
> +        ------
add ValueNotFound to raises

2024-04-20 10:24 UTC, ZixMai commented on invite_service/src/invite_service_impl.py
> +        ------
add ValueNotFound to raises

2024-04-20 10:24 UTC, ZixMai commented on invite_service/src/invite_service_impl.py
> +        ------
add ValueNotFound to raises

2024-04-20 10:25 UTC, ZixMai requested changes
waiting for fixed mistakes

2024-04-20 10:36 UTC, ZixMai requested changes

2024-04-20 10:36 UTC, ZixMai commented on invite_service/repository/mock_invite_repository.py
Annotate class with singleton

2024-04-20 11:32 UTC, ZixMai requested changes

2024-04-20 11:32 UTC, ZixMai commented on invite_service/src/invite_service_impl.py
> +        prisma.errors.PrismaError
remove prisma.errors from raises

2024-04-20 12:47 UTC, ZixMai approved these changes

2024-04-20 12:50 UTC, ZixMai approved these changes

2024-04-20 13:27 UTC, Nhsdkk approved these changes
LGTM

2024-04-20 13:38 UTC, merged