Feat: Create notification service
UnspokenTeam/Calendar pull request #46
Opened 2024-04-18 10:57 UTC by ZixMai

1. Created grpc base for notification service
2. Created db handler for notification service
3. Created notification repository for notification service
4. Created grpc requests methods for notification service
5. Created interceptor for notification service
6. Created proto file for notification service
7. Fixed some issues in event service and dockerfiles

2024-04-19 18:30 UTC, MaxPlays35 approved these changes

2024-04-19 19:57 UTC, Nhsdkk requested changes
Make changes

2024-04-19 19:57 UTC, Nhsdkk commented on notification_service/repository/mock_notification_repository.py
> +            raise ValueNotFoundError("Notifications not found")
Should be "Notification not found"

2024-04-19 19:57 UTC, Nhsdkk commented on notification_service/repository/mock_notification_repository.py
> +class MockNotificationRepositoryImpl(NotificationRepositoryInterface):
Annotate with singleton

2024-04-19 19:57 UTC, Nhsdkk commented on notification_service/repository/notification_repository_impl.py
> +                    "in": [notification_id for notification_id in notifications_ids]
should be just "in": notifications_ids

2024-04-20 13:49 UTC, Nhsdkk requested changes
Make changes

2024-04-20 13:49 UTC, Nhsdkk commented on notification_service/src/notification_service_impl.py
> +    """
add new line

2024-04-20 13:54 UTC, Nhsdkk approved these changes
LGTM

2024-04-20 13:54 UTC, merged