feat: add pagination
UnspokenTeam/Calendar pull request #55
Opened 2024-04-23 17:47 UTC by skelet0no

1) add pagination
2) change messages in proto file
3) update postgres client

2024-04-23 18:21 UTC, ZixMai approved these changes

2024-04-24 19:45 UTC, Nhsdkk commented
Check types in docstrings in invite_service_impl.py

2024-04-24 19:45 UTC, Nhsdkk requested changes
Make changes

2024-04-24 19:45 UTC, Nhsdkk commented on invite_service/repository/mock_invite_repository.py
>          if invites is None or len(invites) == 0:
Check for length after making slice

2024-04-24 19:45 UTC, Nhsdkk commented on invite_service/repository/mock_invite_repository.py
>          if len(self._invites) != 0:
Check for length after making slice

2024-04-24 19:45 UTC, Nhsdkk commented on invite_service/repository/mock_invite_repository.py
>          if invites is None or len(invites) == 0:
Check for length after making slice

2024-04-27 16:34 UTC, MaxPlays35 approved these changes
Well done

2024-04-27 16:34 UTC, Nhsdkk approved these changes
LGTM

2024-04-27 16:35 UTC, Nhsdkk commented on invite_service/repository/mock_invite_repository.py
>          if invites is None or len(invites) == 0:
fixed

2024-04-27 16:35 UTC, Nhsdkk commented on invite_service/repository/mock_invite_repository.py
>          if invites is None or len(invites) == 0:
fixed

2024-04-27 16:35 UTC, Nhsdkk commented on invite_service/repository/mock_invite_repository.py
>          if len(self._invites) != 0:
fixed

2024-04-27 16:35 UTC, merged