Feat: Create delete requests for notification service
UnspokenTeam/Calendar pull request #58
Opened 2024-04-24 20:48 UTC by ZixMai

1.  Updated notification service proto file
2.  Added 4 delete request (by event and author ids, by events and author ids, by author id, by event id)
3.  Changed mock repository delete method
4.  Corrected docstrings in event and notification services

2024-04-26 20:34 UTC, Nhsdkk requested changes
Make changes

2024-04-26 20:34 UTC, Nhsdkk commented on notification_service/repository/mock_notification_repository.py
> +        if indexes is None or len(indexes) == 0:
Redundant check for None

2024-04-26 20:34 UTC, Nhsdkk commented on notification_service/repository/mock_notification_repository.py
> +        if indexes is None or len(indexes) == 0:
Redundant check for None

2024-04-26 20:34 UTC, Nhsdkk commented on notification_service/repository/mock_notification_repository.py
> +        if indexes is None or len(indexes) == 0:
Redundant check for None

2024-04-27 11:48 UTC, MaxPlays35 approved these changes
Good

2024-04-27 12:27 UTC, Nhsdkk approved these changes
LGTM

2024-04-27 12:27 UTC, merged