Feat: Create new requests for event service
UnspokenTeam/Calendar pull request #60
Opened 2024-04-25 09:43 UTC by ZixMai

1.  Added delete events by author id request
2.  Added search by timestamp in get events by aythor id and get all events
3.  Renamed old delete method to delete event by id
4.  Fixed pagination and delete methods in mock

2024-04-27 09:19 UTC, Nhsdkk requested changes
Make changes

2024-04-27 09:19 UTC, Nhsdkk commented on event_service/repository/event_repository_impl.py
> +        Returns page of events those have matches with given list of event ids.
that was right in docstring

2024-04-27 09:19 UTC, Nhsdkk commented on event_service/repository/event_repository_impl.py
> +        Returns page with events those have matches with given author id.
that was right in docstring

2024-04-27 09:19 UTC, Nhsdkk commented on event_service/repository/event_repository_impl.py
> +            List of events those match by author id.
that was right in docstring

2024-04-27 09:19 UTC, Nhsdkk commented on event_service/repository/event_repository_impl.py
> +                else {"start": timestamp}
what about end?

2024-04-27 09:19 UTC, Nhsdkk commented on event_service/repository/event_repository_impl.py
> +            List of events those match by event id.
that was right in docstring

2024-04-27 09:19 UTC, Nhsdkk commented on event_service/repository/event_repository_impl.py
> +            else {"start": timestamp},
where is end?

2024-04-27 09:19 UTC, Nhsdkk commented on event_service/repository/event_repository_interface.py
> +        Returns page with events those have matches with given author id.
that was right in docstring

2024-04-27 09:19 UTC, Nhsdkk commented on event_service/repository/event_repository_interface.py
> +        Returns page of events those have matches with given list of event ids.
that was right in docstring

2024-04-27 09:19 UTC, Nhsdkk commented on event_service/repository/event_repository_interface.py
> +            List of events those match by author id.
that was right in docstring

2024-04-27 09:19 UTC, Nhsdkk commented on event_service/repository/mock_event_repository.py
> +        Returns page with events those have matches with given author id.
that was right in docstring

2024-04-27 09:19 UTC, Nhsdkk commented on event_service/repository/mock_event_repository.py
> +        Returns page of events those have matches with given list of event ids.
that was right in docstring

2024-04-27 09:19 UTC, Nhsdkk commented on event_service/repository/mock_event_repository.py
> +            List of events those match by author id.
that was right in docstring

2024-04-27 09:19 UTC, Nhsdkk commented on event_service/repository/mock_event_repository.py
> +            List of events those match by event id.
that was right in docstring

2024-04-27 09:19 UTC, Nhsdkk commented on event_service/src/event_service_impl.py
> +        Function that need to be bind to the server that deletes events those matches id.
those should be replaced with that

2024-04-27 09:19 UTC, Nhsdkk commented on event_service/src/event_service_impl.py
> +                request.start.seconds + request.start.nanos / 1e9
check for none

2024-04-27 09:19 UTC, Nhsdkk commented on event_service/src/event_service_impl.py
> +            end=datetime.fromtimestamp(request.end.seconds + request.end.nanos / 1e9),
check for none

2024-04-27 09:19 UTC, Nhsdkk commented on event_service/src/event_service_impl.py
> +                request.start.seconds + request.start.nanos / 1e9
check for none

2024-04-27 09:19 UTC, Nhsdkk commented on event_service/src/event_service_impl.py
> +            end=datetime.fromtimestamp(request.end.seconds + request.end.nanos / 1e9),
check for none

2024-04-27 10:05 UTC, ZixMai commented on event_service/repository/event_repository_impl.py
> +                else {"start": timestamp}
this is normal

2024-04-27 10:05 UTC, ZixMai commented on event_service/repository/event_repository_impl.py
> +            else {"start": timestamp},
2 strings upper

2024-04-27 11:35 UTC, MaxPlays35 approved these changes
LGTM

2024-05-01 20:49 UTC, Nhsdkk requested changes
Make changes

2024-05-01 20:49 UTC, Nhsdkk commented on event_service/repository/mock_event_repository.py
> +            index = next(
This function should delete all author's events

2024-05-01 21:05 UTC, Nhsdkk approved these changes
LGTM

2024-05-01 21:05 UTC, merged