Feat: create grpc base for invite service
UnspokenTeam/Calendar pull request #7
Opened 2024-03-24 10:02 UTC by skelet0no

1. Create grpc base
2. Add methods tp grpc
3. Add messages to proto file

2024-03-24 10:23 UTC, Nhsdkk requested changes
Check review and make changes accordingly

2024-03-24 10:23 UTC, Nhsdkk commented on invite_service/main.py
> +    server = grpc.server(futures.ThreadPoolExecutor(max_workers=10))
Switch to async server

2024-03-24 10:23 UTC, Nhsdkk commented on invite_service/proto/invite_service.proto
> +  string id = 1;
Rename to invite_id

2024-03-24 10:23 UTC, Nhsdkk commented on invite_service/proto/invite_service.proto
> +  rpc delete_invite(DeleteInviteRequest) returns (BaseResponse){}
Missing get_invites_by_invitee_id

2024-03-24 10:23 UTC, Nhsdkk commented on invite_service/src/invite_service_impl.py
> +
Missing get_invites_by_invitee_id

2024-03-24 10:23 UTC, Nhsdkk commented on invite_service/src/models/invite.py
> +class Invite:
No docstring here for Invite class

2024-03-24 10:23 UTC, Nhsdkk commented on invite_service/src/models/invite.py
> +from dataclasses import dataclass
No docstring for file

2024-03-24 10:23 UTC, Nhsdkk commented on invite_service/src/models/invite.py
> +    def to_grpc_invite(self) -> GrpcInvite:
No docstring for function

2024-03-25 07:15 UTC, ZixMai requested changes
Big changes in docstrings needed ...

2024-03-25 07:15 UTC, ZixMai commented on invite_service/src/invite_service_impl.py
> +    get_invites_by_user_id()
Add function args

2024-03-25 07:15 UTC, ZixMai commented on invite_service/src/invite_service_impl.py
> +    create_invite()
Add function args

2024-03-25 07:15 UTC, ZixMai commented on invite_service/src/invite_service_impl.py
> +    update_invite()
Add function args

2024-03-25 07:15 UTC, ZixMai commented on invite_service/src/invite_service_impl.py
> +    delete_invite()
Add function args

2024-03-25 07:15 UTC, ZixMai commented on invite_service/src/invite_service_impl.py
> +    def __init__(self):
Add return type

2024-03-25 07:15 UTC, ZixMai commented on invite_service/src/invite_service_impl.py
> +    """
Add empty string at the end of docstring

2024-03-25 07:15 UTC, ZixMai commented on invite_service/src/invite_service_impl.py
> +        request : InvitesByUserIdRequest
Args types in annotations and docstring are different. Add "proto." in docstring to fix

2024-03-25 07:15 UTC, ZixMai commented on invite_service/src/invite_service_impl.py
> +        InvitesResponse
Args types in annotations and docstring are different. Add "proto." in docstring to fix

2024-03-25 07:15 UTC, ZixMai commented on invite_service/src/invite_service_impl.py
> +        """
Add empty line at the end of docstring

2024-03-25 07:15 UTC, ZixMai commented on invite_service/src/invite_service_impl.py
> +        request : InviteeByInviteIdRequest
Args types in annotations and docstring are different. Add "proto.Get" in docstring to fix

2024-03-25 07:15 UTC, ZixMai commented on invite_service/src/invite_service_impl.py
> +        InvitesResponse
Args types in annotations and docstring are different. Add "proto." in docstring to fix

2024-03-25 07:15 UTC, ZixMai commented on invite_service/src/invite_service_impl.py
> +        """
Add empty string at the end of docstring

2024-03-25 07:15 UTC, ZixMai commented on invite_service/src/invite_service_impl.py
> +        request : GrpcInvite
Args types in annotations and docstring are different. Remove "GrpcInvite", add "proto.Invite" instead in docstring to fix

2024-03-25 07:15 UTC, ZixMai commented on invite_service/src/invite_service_impl.py
> +        BaseResponse
Args types in annotations and docstring are different. Add "proto." in docstring to fix

2024-03-25 07:15 UTC, ZixMai commented on invite_service/src/invite_service_impl.py
> +        """
Add empty line at the end of docstring

2024-03-25 07:15 UTC, ZixMai commented on invite_service/src/invite_service_impl.py
> +        request : DeleteInviteRequest
Args types in annotations and docstring are different. Add "proto." in docstring to fix

2024-03-25 07:15 UTC, ZixMai commented on invite_service/src/invite_service_impl.py
> +        BaseResponse
Args types in annotations and docstring are different. Add "proto." in docstring to fix

2024-03-25 07:15 UTC, ZixMai commented on invite_service/src/invite_service_impl.py
> +        """
Add empty string at the end of docstring

2024-03-25 07:15 UTC, ZixMai commented on invite_service/src/invite_service_impl.py
> +        BaseResponse
Args types in annotations and docstring are different. Add "proto." in docstring to fix

2024-03-25 07:15 UTC, ZixMai commented on invite_service/src/invite_service_impl.py
> +        """
Add empty line at the end of docstring

2024-03-25 07:15 UTC, ZixMai commented on invite_service/src/invite_service_impl.py
> +        request : GrpcInvite
Args types in annotations and docstring are different. Remove "GrpcInvite", add "proto.Invite" instead in docstring to fix

2024-03-25 07:15 UTC, ZixMai commented on invite_service/src/models/invite.py
> +    to_grpc_invite()
Add arguments to method in docstring

2024-03-25 07:15 UTC, ZixMai commented on invite_service/src/models/invite.py
> +        """
Add empty line at the end of docstring

2024-03-25 08:38 UTC, ZixMai requested changes

2024-03-25 08:38 UTC, ZixMai commented on invite_service/main.py
> +async def serve():
Add return type

2024-03-26 18:53 UTC, ZixMai approved these changes

2024-03-26 19:04 UTC, Nhsdkk approved these changes
LGTM

2024-03-27 17:40 UTC, MaxPlays35 approved these changes

2024-03-27 17:56 UTC, Nhsdkk requested changes
Check my review

2024-03-27 17:56 UTC, Nhsdkk commented on invite_service/main.py
> +async def serve():
Should return None

2024-03-27 17:56 UTC, Nhsdkk commented on invite_service/src/models/invite.py
> +        ID of the user
Should be ID of the event

2024-03-27 17:56 UTC, Nhsdkk commented on invite_service/src/models/invite.py
> +    Data class that stores user information
Should be "Data class that stores invite information"

2024-03-27 17:56 UTC, Nhsdkk commented on invite_service/src/models/invite.py
> +        invite = GrpcInvite(
Make return statement here

2024-03-27 17:56 UTC, Nhsdkk commented on invite_service/src/invite_service_impl.py
> +
Where is docs for get_invites_by_invitee_id

2024-03-27 18:04 UTC, Nhsdkk commented on invite_service/src/models/invite.py
> +        ID of the user
invite sorry

2024-03-27 18:09 UTC, Nhsdkk approved these changes
LGTM

2024-03-27 18:10 UTC, merged