Feat/add notification route to gateway
UnspokenTeam/Calendar pull request #73
Opened 2024-04-30 13:50 UTC by Nhsdkk

1) Add GET: /notification/{notification_id} route to get notification by id
2) Add GET: /notification/amdin/all/ route to get all notifications
3) Add GET: /notification/my/ route to get user's notifications
4) Add POST: /notification/ route to create notification
5) Add PUT: /notification/ route to update notification data as author
6) Add PUT: /notification/admin/ route to update notification as admin
7) Add DELETE: /notification/ route to delete notification

2024-04-30 15:34 UTC, MaxPlays35 commented on gateway/app/grpc_client/grpc_client.py
> +        # """
It looks weird

2024-05-01 09:31 UTC, ZixMai requested changes

2024-05-01 09:31 UTC, ZixMai commented on gateway/app/models/notification.py
> +    enabled: bool
must be with default value = True

2024-05-01 09:31 UTC, ZixMai commented on gateway/app/models/notification.py
> +        notification.created_at.FromDatetime(self.created_at)
needs to be with utc tz

2024-05-01 09:31 UTC, ZixMai commented on gateway/app/models/notification.py
> +            notification.deleted_at.FromDatetime(self.deleted_at)
needs to be with utc tz

2024-05-01 10:03 UTC, ZixMai approved these changes

2024-05-01 17:03 UTC, ZixMai approved these changes

2024-05-01 20:38 UTC, MaxPlays35 approved these changes

2024-05-01 21:14 UTC, ZixMai approved these changes

2024-05-01 21:14 UTC, merged