Fix: Add return objects for requests and correct return types in proto for invite service
UnspokenTeam/Calendar pull request #83
Opened 2024-05-02 18:20 UTC by skelet0no

1. Added return objects for requests.
2. Corrected return types in proto for invite service.
3. Moved big queries to constants and made query more readable.

2024-05-02 18:25 UTC, MaxPlays35 approved these changes

2024-05-02 23:41 UTC, ZixMai approved these changes

2024-05-02 23:41 UTC, ZixMai commented on invite_service/repository/invite_repository_impl.py
> +            return await self._db_client.db.invite.create(
wrong return type

2024-05-02 23:41 UTC, ZixMai commented on invite_service/repository/invite_repository_impl.py
> +        return await self.update_invite(db_invite)
wrong return type

2024-05-02 23:41 UTC, ZixMai commented on invite_service/repository/invite_repository_impl.py
> +        return invites
wrong returning object

2024-05-02 23:41 UTC, ZixMai commented on invite_service/repository/invite_repository_impl.py
> +        return await self._db_client.db.invite.update(
wrong return type

2024-05-03 06:36 UTC, ZixMai requested changes
Make changes

2024-05-04 18:56 UTC, ZixMai requested changes

2024-05-04 18:56 UTC, ZixMai commented on invite_service/repository/mock_invite_repository.py
>              invite.deleted_at = None
add line with invite.status = InviteStatus.PENDING

2024-05-04 18:56 UTC, ZixMai commented on invite_service/repository/mock_invite_repository.py
> +            invite.deleted_at = None
add definition of created_at and status field

2024-05-04 19:05 UTC, ZixMai approved these changes

2024-05-04 22:08 UTC, Nhsdkk requested changes
Make changes

2024-05-04 22:08 UTC, Nhsdkk commented on invite_service/repository/invite_repository_impl.py
> +            return Invite.from_prisma_invite(await self.update_invite(db_invite))
Why are you calling another method in transaction. you should use transaction client here

2024-05-04 22:08 UTC, Nhsdkk commented on invite_service/repository/invite_repository_impl.py
> +                where={"id": invite.id}, data=invite.to_dict()
deleted_at should be none

2024-05-04 22:08 UTC, Nhsdkk commented on invite_service/repository/mock_invite_repository.py
> +            if any(
you should check this once

2024-05-05 14:13 UTC, skelet0no commented on invite_service/repository/invite_repository_impl.py
> +                where={"id": invite.id}, data=invite.to_dict()
Wont do it

2024-05-05 22:59 UTC, Nhsdkk approved these changes
LGTM

2024-05-05 23:00 UTC, merged