Feat: Create readme for event service
UnspokenTeam/Calendar pull request #87
Opened 2024-05-03 18:36 UTC by ZixMai

1.  Created readme for event service

2024-05-04 15:03 UTC, Nhsdkk approved these changes
LGTM

2024-05-04 21:43 UTC, Nhsdkk requested changes
Make changes

2024-05-04 21:43 UTC, Nhsdkk commented on event_service/README.md
> +	DATABASE_URL="DATABASE_URL"
Add comments about variables

2024-05-04 21:43 UTC, Nhsdkk commented on event_service/README.md
> +	2. **Через poetry**
Add proto and prisma client generate steps

2024-05-05 23:04 UTC, Nhsdkk requested changes
Make changes

2024-05-05 23:04 UTC, Nhsdkk commented on event_service/README.md
> +	- где:
Move this to comments inside dotenv example

2024-05-05 23:04 UTC, Nhsdkk commented on event_service/README.md
> +2. **Установка**:
Add pre-installation step to create db

2024-05-06 12:45 UTC, MaxPlays35 approved these changes

2024-05-07 20:51 UTC, Nhsdkk approved these changes
LGTM

2024-05-07 20:52 UTC, merged