Feat: Create README.md for notification service
UnspokenTeam/Calendar pull request #90
Opened 2024-05-03 22:08 UTC by ZixMai

1.  Created README.md for notification service

2024-05-04 15:02 UTC, Nhsdkk approved these changes
LGTM

2024-05-04 21:39 UTC, Nhsdkk requested changes
Make changes

2024-05-04 21:39 UTC, Nhsdkk commented on notification_service/README.md
> +	2. **Через poetry**
Add proto and prisma client generate steps

2024-05-04 21:39 UTC, Nhsdkk commented on notification_service/README.md
> +	DATABASE_URL="DATABASE_URL"
Add comments for variables

2024-05-05 23:03 UTC, Nhsdkk requested changes
Make changes

2024-05-05 23:03 UTC, Nhsdkk commented on notification_service/README.md
> + 	- где:
Move this to comments inside dotenv example

2024-05-05 23:03 UTC, Nhsdkk commented on notification_service/README.md
> +	- Доступно несколько способов установки.
Add pre-installation step to create db

2024-05-06 12:46 UTC, MaxPlays35 approved these changes

2024-05-07 20:50 UTC, Nhsdkk approved these changes
LGTM

2024-05-07 20:50 UTC, merged