Feat: Create README.md for invite service
UnspokenTeam/Calendar pull request #91
Opened 2024-05-04 15:40 UTC by skelet0no

Created README.md for invite service

2024-05-04 18:45 UTC, ZixMai approved these changes

2024-05-04 21:41 UTC, Nhsdkk requested changes
Make changes

2024-05-04 21:41 UTC, Nhsdkk commented on invite_service/README.md
> +	DATABASE_URL="DATABASE_URL"
Add comments for variables

2024-05-04 21:41 UTC, Nhsdkk commented on invite_service/README.md
> +	2. **Через poetry**
Add proto and prisma client generate steps

2024-05-05 23:02 UTC, Nhsdkk requested changes
Make changes

2024-05-05 23:02 UTC, Nhsdkk commented on invite_service/README.md
> + 	- где:
Move this to comments inside dotenv example

2024-05-05 23:02 UTC, Nhsdkk commented on invite_service/README.md
> +2. **Установка**:
Add pre-installation step to create db

2024-05-07 19:19 UTC, MaxPlays35 approved these changes

2024-05-07 20:27 UTC, Nhsdkk requested changes
Make changes

2024-05-07 20:27 UTC, Nhsdkk commented on invite_service/README.md
> +2. Подготовить локальный инстанс redis ([Setup redis with docker](https://redis.io/docs/latest/operate/oss_and_stack/install/install-stack/docker/))
Delete this step

2024-05-09 08:59 UTC, Nhsdkk approved these changes
LGTM

2024-05-09 09:00 UTC, merged