Feat: Create README for identity service
UnspokenTeam/Calendar pull request #94
Opened 2024-05-04 20:55 UTC by ZixMai

1. Created README for identity service

2024-05-04 21:28 UTC, MaxPlays35 approved these changes

2024-05-04 21:37 UTC, Nhsdkk requested changes
Make changes

2024-05-04 21:37 UTC, Nhsdkk commented on identity_service/README.md
> +	DATABASE_URL="DATABASE_URL"
Wrong env format. Should be 
```
ACCESS_SECRET = "***"
REFRESH_SECRET = "***"
DATABASE_URL = "***"
ENVIRONMENT = "***"
ACCESS_TOKEN_EXPIRATION = 15
REFRESH_TOKEN_EXPIRATION = 30
```

2024-05-04 21:37 UTC, Nhsdkk commented on identity_service/README.md
> +        - Также возможен локальный запуск при помощи утилиты poetry **без использования docker'a**. Для этого введите и выполните команду:
Add generate proto and prisma steps

2024-05-04 21:37 UTC, Nhsdkk commented on identity_service/README.md
> +        - **register** - **Создание токенов при регистрации пользователя**
Just user registration

2024-05-04 21:37 UTC, Nhsdkk commented on identity_service/README.md
> +        - **auth** - **Получение ID аунтефицированного пользователя**
Just retrieval of user data

2024-05-05 22:57 UTC, Nhsdkk requested changes
Make changes

2024-05-05 22:57 UTC, Nhsdkk commented on identity_service/README.md
> +	ENVIRONMENT="ENVIRONMENT"
Add comments about variables

2024-05-05 22:57 UTC, Nhsdkk commented on identity_service/README.md
> +    - где:
Its better to use comments inside env example

2024-05-05 22:57 UTC, Nhsdkk commented on identity_service/README.md
>  2. **Установка**:
Add setup database step

2024-05-05 22:57 UTC, Nhsdkk commented on identity_service/README.md
> +poetry run python -m grpc_tools.protoc -I ../shared/proto --python_out=generated --grpc_python_out=generated --pyi_out=generated ../shared/proto/user/*.proto ../shared/proto/notification_service/*.pr
wtf is this

2024-05-07 16:03 UTC, Nhsdkk approved these changes
LGTM

2024-05-07 16:03 UTC, merged